server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update

auth:
  jwt:
    secret: SuperSecretKeyForJwtSigningWhyNotChangeMe!
    expirationMs: 900000
    refreshExpirationMs: 86400000
