server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: yourdbuser
    password: yourdbpassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

auth:
  jwt:
    private-key: classpath:private.pem
    public-key: classpath:public.pem
    expirationMs: 900000           # 15 minutes
    refreshExpirationMs: 86400000 # 24 heures

security:
  cookie:
    secure=false: