name: Pull Request Workflow
on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Inject private and public keys
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.PRIVATE_KEY }}" | sed 's/\\n/\n/g' > src/main/resources/private.pem
          echo "${{ secrets.PUBLIC_KEY }}" | sed 's/\\n/\n/g' > src/main/resources/public.pem
      

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: mvn clean verify

  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - uses: actions/checkout@v4

      - name: Inject private and public keys
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.PRIVATE_KEY }}" | sed 's/\\n/\n/g' > src/main/resources/private.pem
          echo "${{ secrets.PUBLIC_KEY }}" | sed 's/\\n/\n/g' > src/main/resources/public.pem
      

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and analyze on SonarCloud
        run: |
          mvn clean verify sonar:sonar -DskipTests=true \
            -Dsonar.projectKey=PayeTonKawa2025_auth-service \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
            -Dsonar.pullrequest.branch=${{ github.head_ref }} \
            -Dsonar.pullrequest.base=${{ github.base_ref }}
